In [1]:
import pandas as pd

data_source = "/home/fra/DataMart/datacentre/olddata/"
train_file = "adult_train.csv"
test_file = "adult_test.csv"

# load data
trainData = pd.read_csv(data_source + train_file)
trainData.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [2]:
import sys
mylib = '/home/fra/Project/pyProj/mlib'

In [3]:
sys.path.append(mylib)

In [4]:
import transform as trf
import pipeline as pl

### target transform

In [5]:
target_col = 'INCOME'

In [6]:
tpipeline = pl.make_target_pipeline(target_col)

In [7]:
out = tpipeline.fit_transform(trainData)

In [8]:
out

array([0, 0, 0, ..., 0, 0, 1])

In [9]:
mapping = {' <=50K': 1, ' >50K': 0}

In [10]:
mpipeline = pl.make_target_pipeline(target_col, mapping)

In [11]:
out = mpipeline.fit_transform(trainData)

In [12]:
out

array([1, 1, 1, ..., 1, 1, 0])

### feature transform

In [13]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, OrdinalEncoder

In [14]:
from imp import reload
import numpy as np

In [149]:
reload(trf)
reload(pl)

<module 'pipeline' from '/home/fra/Project/pyProj/mlib/pipeline.py'>

In [15]:
ntransformer = StandardScaler
ctransformer = OrdinalEncoder
# px = pl.make_feature_pipeline(ntransformer, ctransformer, target_col, [])

### Standard Pipeline

In [16]:
(X, y, features, py, px) = pl.standard_feature_preprocess(trainData, target_col, ntransformer, ctransformer)

In [17]:
features

Index(['AGE', 'WORKCLASS', 'FNLWGT', 'EDUCATION', 'EDUCATION-NUM',
       'MARITAL-STATUS', 'OCCUPATION', 'RELATIONSHIP', 'RACE', 'SEX',
       'CAPITAL-GAIN', 'CAPITAL-LOSS', 'HOURS-PER-WEEK', 'NATIVE-COUNTRY'],
      dtype='object')

In [18]:
X.shape, y.shape, features.shape

((32561, 14), (32561,), (14,))

In [19]:
yy = py.transform(trainData)

In [20]:
np.all(yy == y)

True

In [21]:
XX = px.transform(trainData)

In [22]:
np.all(XX == X)

True

In [23]:
X

array([[ 3.06705574e-02,  7.00000000e+00, -1.06361075e+00, ...,
        -2.16659527e-01, -3.54294470e-02,  3.90000000e+01],
       [ 8.37108980e-01,  6.00000000e+00, -1.00870700e+00, ...,
        -2.16659527e-01, -2.22215312e+00,  3.90000000e+01],
       [-4.26420266e-02,  4.00000000e+00,  2.45078505e-01, ...,
        -2.16659527e-01, -3.54294470e-02,  3.90000000e+01],
       ...,
       [ 1.42360965e+00,  4.00000000e+00, -3.58777414e-01, ...,
        -2.16659527e-01, -3.54294470e-02,  3.90000000e+01],
       [-1.21564337e+00,  4.00000000e+00,  1.10959884e-01, ...,
        -2.16659527e-01, -1.65522476e+00,  3.90000000e+01],
       [ 9.83734148e-01,  5.00000000e+00,  9.29892576e-01, ...,
        -2.16659527e-01, -3.54294470e-02,  3.90000000e+01]])

In [24]:
type(XX), type(X)

(pandas.core.frame.DataFrame, numpy.ndarray)

In [25]:
XX

AGE  WORKCLASS    FNLWGT  EDUCATION  EDUCATION-NUM  \
0      0.030671        7.0 -1.063611        9.0       1.134739   
1      0.837109        6.0 -1.008707        9.0       1.134739   
2     -0.042642        4.0  0.245079       11.0      -0.420060   
3      1.057047        4.0  0.425801        1.0      -1.197459   
4     -0.775768        4.0  1.408176        9.0       1.134739   
...         ...        ...       ...        ...            ...   
32556 -0.849080        4.0  0.639741        7.0       0.746039   
32557  0.103983        4.0 -0.335433       11.0      -0.420060   
32558  1.423610        4.0 -0.358777       11.0      -0.420060   
32559 -1.215643        4.0  0.110960       11.0      -0.420060   
32560  0.983734        5.0  0.929893       11.0      -0.420060   

       MARITAL-STATUS  OCCUPATION  RELATIONSHIP  RACE  SEX  CAPITAL-GAIN  \
0                 4.0         1.0           1.0   4.0  1.0      0.148453   
1                 2.0         4.0           0.0   4.0  1.0     -0.145920   
2                 0.0         6.0           1.0   4.0  1.0     -0.145920   
3                 2.0         6.0           0.0   2.0  1.0     -0.145920   
4                 2.0        10.0           5.0   2.0  0.0     -0.145920   
...               ...         ...           ...   ...  ...           ...   
32556             2.0        13.0           5.0   4.0  0.0     -0.145920   
32557             2.0         7.0           0.0   4.0  1.0     -0.145920   
32558             6.0         1.0           4.0   4.0  0.0     -0.145920   
32559             4.0         1.0           3.0   4.0  1.0     -0.145920   
32560             2.0         4.0           5.0   4.0  0.0      1.888424   

       CAPITAL-LOSS  HOURS-PER-WEEK  NATIVE-COUNTRY  
0          -0.21666       -0.035429            39.0  
1          -0.21666       -2.222153            39.0  
2          -0.21666       -0.035429            39.0  
3          -0.21666       -0.035429            39.0  
4          -0.21666       -0.035429             5.0  
...             ...             ...             ...  
32556      -0.21666       -0.197409            39.0  
32557      -0.21666       -0.035429            39.0  
32558      -0.21666       -0.035429            39.0  
32559      -0.21666       -1.655225            39.0  
32560      -0.21666       -0.035429            39.0  

[32561 rows x 14 columns]

### Dummy Pipeline

In [31]:
reload(trf)
reload(pl)


<module 'pipeline' from '/home/fra/Project/pyProj/mlib/pipeline.py'>

In [32]:
(dX, dy, dfeatures, dpy, dpx) = pl.dummy_feature_preprocess(trainData, target_col)

In [33]:
dX.shape, dy.shape, dfeatures.shape

((32561, 108), (32561,), (108,))

In [34]:
dfeatures

Index(['AGE', 'FNLWGT', 'EDUCATION-NUM', 'CAPITAL-GAIN', 'CAPITAL-LOSS',
       'HOURS-PER-WEEK', 'WORKCLASS_ ?', 'WORKCLASS_ Federal-gov',
       'WORKCLASS_ Local-gov', 'WORKCLASS_ Never-worked',
       ...
       'NATIVE-COUNTRY_ Portugal', 'NATIVE-COUNTRY_ Puerto-Rico',
       'NATIVE-COUNTRY_ Scotland', 'NATIVE-COUNTRY_ South',
       'NATIVE-COUNTRY_ Taiwan', 'NATIVE-COUNTRY_ Thailand',
       'NATIVE-COUNTRY_ Trinadad&Tobago', 'NATIVE-COUNTRY_ United-States',
       'NATIVE-COUNTRY_ Vietnam', 'NATIVE-COUNTRY_ Yugoslavia'],
      dtype='object', length=108)

In [35]:
yy = dpy.transform(trainData)

In [36]:
np.all(yy == dy)

True

In [37]:
XX = dpx.transform(trainData)

In [38]:
XX.head()

AGE    FNLWGT  EDUCATION-NUM  CAPITAL-GAIN  CAPITAL-LOSS  \
0  0.030671 -1.063611       1.134739      0.148453      -0.21666   
1  0.837109 -1.008707       1.134739     -0.145920      -0.21666   
2 -0.042642  0.245079      -0.420060     -0.145920      -0.21666   
3  1.057047  0.425801      -1.197459     -0.145920      -0.21666   
4 -0.775768  1.408176       1.134739     -0.145920      -0.21666   

   HOURS-PER-WEEK  WORKCLASS_ ?  WORKCLASS_ Federal-gov  WORKCLASS_ Local-gov  \
0       -0.035429             0                       0                     0   
1       -2.222153             0                       0                     0   
2       -0.035429             0                       0                     0   
3       -0.035429             0                       0                     0   
4       -0.035429             0                       0                     0   

   WORKCLASS_ Never-worked  ...  NATIVE-COUNTRY_ Portugal  \
0                        0  ...                         0   
1                        0  ...                         0   
2                        0  ...                         0   
3                        0  ...                         0   
4                        0  ...                         0   

   NATIVE-COUNTRY_ Puerto-Rico  NATIVE-COUNTRY_ Scotland  \
0                            0                         0   
1                            0                         0   
2                            0                         0   
3                            0                         0   
4                            0                         0   

   NATIVE-COUNTRY_ South  NATIVE-COUNTRY_ Taiwan  NATIVE-COUNTRY_ Thailand  \
0                      0                       0                         0   
1                      0                       0                         0   
2                      0                       0                         0   
3                      0                       0                         0   
4                      0                       0                         0   

   NATIVE-COUNTRY_ Trinadad&Tobago  NATIVE-COUNTRY_ United-States  \
0                                0                              1   
1                                0                              1   
2                                0                              1   
3                                0                              1   
4                                0                              0   

   NATIVE-COUNTRY_ Vietnam  NATIVE-COUNTRY_ Yugoslavia  
0                        0                           0  
1                        0                           0  
2                        0                           0  
3                        0                           0  
4                        0                           0  

[5 rows x 108 columns]

In [39]:
dX

array([[ 0.03067056, -1.06361075,  1.13473876, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.83710898, -1.008707  ,  1.13473876, ...,  1.        ,
         0.        ,  0.        ],
       [-0.04264203,  0.2450785 , -0.42005962, ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [ 1.42360965, -0.35877741, -0.42005962, ...,  1.        ,
         0.        ,  0.        ],
       [-1.21564337,  0.11095988, -0.42005962, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.98373415,  0.92989258, -0.42005962, ...,  1.        ,
         0.        ,  0.        ]])

In [40]:
np.all(XX == dX)

True

### DEBUG

In [39]:
import explore as ex
categoricalCols = ex.get_column_for_type(trainData, 'object')

In [40]:
categoricalCols

['WORKCLASS',
 'EDUCATION',
 'MARITAL-STATUS',
 'OCCUPATION',
 'RELATIONSHIP',
 'RACE',
 'SEX',
 'NATIVE-COUNTRY',
 'INCOME']

In [41]:
ctransformer().fit_transform(trainData[categoricalCols])

WORKCLASS_ ?  WORKCLASS_ Federal-gov  WORKCLASS_ Local-gov  \
0                 0                       0                     0   
1                 0                       0                     0   
2                 0                       0                     0   
3                 0                       0                     0   
4                 0                       0                     0   
...             ...                     ...                   ...   
32556             0                       0                     0   
32557             0                       0                     0   
32558             0                       0                     0   
32559             0                       0                     0   
32560             0                       0                     0   

       WORKCLASS_ Never-worked  WORKCLASS_ Private  WORKCLASS_ Self-emp-inc  \
0                            0                   0                        0   
1                            0                   0                        0   
2                            0                   1                        0   
3                            0                   1                        0   
4                            0                   1                        0   
...                        ...                 ...                      ...   
32556                        0                   1                        0   
32557                        0                   1                        0   
32558                        0                   1                        0   
32559                        0                   1                        0   
32560                        0                   0                        1   

       WORKCLASS_ Self-emp-not-inc  WORKCLASS_ State-gov  \
0                                0                     1   
1                                1                     0   
2                                0                     0   
3                                0                     0   
4                                0                     0   
...                            ...                   ...   
32556                            0                     0   
32557                            0                     0   
32558                            0                     0   
32559                            0                     0   
32560                            0                     0   

       WORKCLASS_ Without-pay  EDUCATION_ 10th  ...  NATIVE-COUNTRY_ Scotland  \
0                           0                0  ...                         0   
1                           0                0  ...                         0   
2                           0                0  ...                         0   
3                           0                0  ...                         0   
4                           0                0  ...                         0   
...                       ...              ...  ...                       ...   
32556                       0                0  ...                         0   
32557                       0                0  ...                         0   
32558                       0                0  ...                         0   
32559                       0                0  ...                         0   
32560                       0                0  ...                         0   

       NATIVE-COUNTRY_ South  NATIVE-COUNTRY_ Taiwan  \
0                          0                       0   
1                          0                       0   
2                          0                       0   
3                          0                       0   
4                          0                       0   
...                      ...                     ...   
32556                      0                       0   
32557                      0                       0   
32558                      0   

In [42]:
numericCols = ex.get_column_for_type(trainData, 'int64')

In [43]:
numericCols

['AGE',
 'FNLWGT',
 'EDUCATION-NUM',
 'CAPITAL-GAIN',
 'CAPITAL-LOSS',
 'HOURS-PER-WEEK']

In [47]:
ntransformer().fit_transform(trainData[numericCols])

AGE    FNLWGT  EDUCATION-NUM  CAPITAL-GAIN  CAPITAL-LOSS  \
0      0.030671 -1.063611       1.134739      0.148453      -0.21666   
1      0.837109 -1.008707       1.134739     -0.145920      -0.21666   
2     -0.042642  0.245079      -0.420060     -0.145920      -0.21666   
3      1.057047  0.425801      -1.197459     -0.145920      -0.21666   
4     -0.775768  1.408176       1.134739     -0.145920      -0.21666   
...         ...       ...            ...           ...           ...   
32556 -0.849080  0.639741       0.746039     -0.145920      -0.21666   
32557  0.103983 -0.335433      -0.420060     -0.145920      -0.21666   
32558  1.423610 -0.358777      -0.420060     -0.145920      -0.21666   
32559 -1.215643  0.110960      -0.420060     -0.145920      -0.21666   
32560  0.983734  0.929893      -0.420060      1.888424      -0.21666   

       HOURS-PER-WEEK  
0           -0.035429  
1           -2.222153  
2           -0.035429  
3           -0.035429  
4           -0.035429  
...               ...  
32556       -0.197409  
32557       -0.035429  
32558       -0.035429  
32559       -1.655225  
32560       -0.035429  

[32561 rows x 6 columns]

In [48]:
ntransformer().fit_transform(trainData[numericCols].to_numpy())

array([[ 0.03067056, -1.06361075,  1.13473876,  0.1484529 , -0.21665953,
        -0.03542945],
       [ 0.83710898, -1.008707  ,  1.13473876, -0.14592048, -0.21665953,
        -2.22215312],
       [-0.04264203,  0.2450785 , -0.42005962, -0.14592048, -0.21665953,
        -0.03542945],
       ...,
       [ 1.42360965, -0.35877741, -0.42005962, -0.14592048, -0.21665953,
        -0.03542945],
       [-1.21564337,  0.11095988, -0.42005962, -0.14592048, -0.21665953,
        -1.65522476],
       [ 0.98373415,  0.92989258, -0.42005962,  1.88842434, -0.21665953,
        -0.03542945]])

### One Hot Encoder

In [49]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')

In [54]:
ans = enc.fit_transform(trainData[categoricalCols]).toarray()

In [55]:
ans.shape

(32561, 104)

In [56]:
categoricalCols

['WORKCLASS',
 'EDUCATION',
 'MARITAL-STATUS',
 'OCCUPATION',
 'RELATIONSHIP',
 'RACE',
 'SEX',
 'NATIVE-COUNTRY',
 'INCOME']

### Dummy Transformer

In [61]:
dum = trf.DummyTransformer()

In [62]:
X = [['Male', 1], ['Female', 3], ['Female', 2]]
df = pd.DataFrame(X)

In [63]:
df

0  1
0    Male  1
1  Female  3
2  Female  2

In [64]:
dum.fit_transform(df)

1  0_Female  0_Male
0  1         0       1
1  3         1       0
2  2         1       0

In [65]:
XX = [['Male', 1], ['Female', 3], ['Child', 2]]
testdf = pd.DataFrame(XX)

In [66]:
dum.transform(testdf)

1  0_Child  0_Female  0_Male
0  1        0         0       1
1  3        0         1       0
2  2        1         0       0

### Categorical Transformer

In [67]:
out = trf.CategoricalEncoder().fit_transform(trainData)

In [68]:
out.head()

AGE  WORKCLASS  FNLWGT  EDUCATION  EDUCATION-NUM  MARITAL-STATUS  \
0   39        7.0   77516        9.0             13             4.0   
1   50        6.0   83311        9.0             13             2.0   
2   38        4.0  215646       11.0              9             0.0   
3   53        4.0  234721        1.0              7             2.0   
4   28        4.0  338409        9.0             13             2.0   

   OCCUPATION  RELATIONSHIP  RACE  SEX  CAPITAL-GAIN  CAPITAL-LOSS  \
0         1.0           1.0   4.0  1.0          2174             0   
1         4.0           0.0   4.0  1.0             0             0   
2         6.0           1.0   4.0  1.0             0             0   
3         6.0           0.0   2.0  1.0             0             0   
4        10.0           5.0   2.0  0.0             0             0   

   HOURS-PER-WEEK  NATIVE-COUNTRY  INCOME  
0              40            39.0     0.0  
1              13            39.0     0.0  
2              40            39.0     0.0  
3              40            39.0     0.0  
4              40             5.0     0.0

In [69]:
out = trf.CategoricalEncoder().fit_transform(trainData[numericCols])
out.head()

AGE  FNLWGT  EDUCATION-NUM  CAPITAL-GAIN  CAPITAL-LOSS  HOURS-PER-WEEK
0   39   77516             13          2174             0              40
1   50   83311             13             0             0              13
2   38  215646              9             0             0              40
3   53  234721              7             0             0              40
4   28  338409             13             0             0              40

In [70]:
trainData[numericCols].head()

AGE  FNLWGT  EDUCATION-NUM  CAPITAL-GAIN  CAPITAL-LOSS  HOURS-PER-WEEK
0   39   77516             13          2174             0              40
1   50   83311             13             0             0              13
2   38  215646              9             0             0              40
3   53  234721              7             0             0              40
4   28  338409             13             0             0              40