In [270]:
import os, sys
import pandas as pd

In [271]:
sys.path.append('..')

In [272]:
import utility as ut

In [4]:
data_file = "abalone.csv"
df = pd.read_csv("../data/"+data_file)
df.head()

sex  length  diameter  height  whole_wt  shucked_wt  viscera_wt  shell_wt  \
0   M   0.455     0.365   0.095    0.5140      0.2245      0.1010     0.150   
1   M   0.350     0.265   0.090    0.2255      0.0995      0.0485     0.070   
2   F   0.530     0.420   0.135    0.6770      0.2565      0.1415     0.210   
3   M   0.440     0.365   0.125    0.5160      0.2155      0.1140     0.155   
4   I   0.330     0.255   0.080    0.2050      0.0895      0.0395     0.055   

   rings  
0     15  
1      7  
2      9  
3     10  
4      7

In [11]:
pd.melt(df, id_vars=['sex'], value_vars=['rings'])

sex variable  value
0      M    rings     15
1      M    rings      7
2      F    rings      9
3      M    rings     10
4      I    rings      7
...   ..      ...    ...
4172   F    rings     11
4173   M    rings     10
4174   M    rings      9
4175   F    rings     10
4176   M    rings     12

[4177 rows x 3 columns]

In [12]:
pd.melt(df, id_vars=['rings'], value_vars=['sex'])

rings variable value
0        15      sex     M
1         7      sex     M
2         9      sex     F
3        10      sex     M
4         7      sex     I
...     ...      ...   ...
4172     11      sex     F
4173     10      sex     M
4174      9      sex     M
4175     10      sex     F
4176     12      sex     M

[4177 rows x 3 columns]

In [14]:
df.iloc[0]

index              0
sex                M
length         0.455
diameter       0.365
height         0.095
whole_wt       0.514
shucked_wt    0.2245
viscera_wt     0.101
shell_wt        0.15
rings             15
Name: 0, dtype: object

In [16]:
ut.discretize_column(df, 'rings')

index sex  length  diameter  height  whole_wt  shucked_wt  viscera_wt  \
0         0   M   0.455     0.365   0.095    0.5140      0.2245      0.1010   
1         1   M   0.350     0.265   0.090    0.2255      0.0995      0.0485   
2         2   F   0.530     0.420   0.135    0.6770      0.2565      0.1415   
3         3   M   0.440     0.365   0.125    0.5160      0.2155      0.1140   
4         4   I   0.330     0.255   0.080    0.2050      0.0895      0.0395   
...     ...  ..     ...       ...     ...       ...         ...         ...   
4172   4172   F   0.565     0.450   0.165    0.8870      0.3700      0.2390   
4173   4173   M   0.590     0.440   0.135    0.9660      0.4390      0.2145   
4174   4174   M   0.600     0.475   0.205    1.1760      0.5255      0.2875   
4175   4175   F   0.625     0.485   0.150    1.0945      0.5310      0.2610   
4176   4176   M   0.710     0.555   0.195    1.9485      0.9455      0.3765   

      shell_wt  rings rings_GRP  
0       0.1500     15      High  
1       0.0700      7       Low  
2       0.2100      9       Mid  
3       0.1550     10       Mid  
4       0.0550      7       Low  
...        ...    ...       ...  
4172    0.2490     11       Mid  
4173    0.2605     10       Mid  
4174    0.3080      9       Mid  
4175    0.2960     10       Mid  
4176    0.4950     12      High  

[4177 rows x 11 columns]

In [17]:
ut.discretize_column(df, 'rings', num_bins=5)

index sex  length  diameter  height  whole_wt  shucked_wt  viscera_wt  \
0         0   M   0.455     0.365   0.095    0.5140      0.2245      0.1010   
1         1   M   0.350     0.265   0.090    0.2255      0.0995      0.0485   
2         2   F   0.530     0.420   0.135    0.6770      0.2565      0.1415   
3         3   M   0.440     0.365   0.125    0.5160      0.2155      0.1140   
4         4   I   0.330     0.255   0.080    0.2050      0.0895      0.0395   
...     ...  ..     ...       ...     ...       ...         ...         ...   
4172   4172   F   0.565     0.450   0.165    0.8870      0.3700      0.2390   
4173   4173   M   0.590     0.440   0.135    0.9660      0.4390      0.2145   
4174   4174   M   0.600     0.475   0.205    1.1760      0.5255      0.2875   
4175   4175   F   0.625     0.485   0.150    1.0945      0.5310      0.2610   
4176   4176   M   0.710     0.555   0.195    1.9485      0.9455      0.3765   

      shell_wt  rings     rings_GRP  
0       0.1500     15  (12.0, 29.0]  
1       0.0700      7  (0.999, 7.0]  
2       0.2100      9    (7.0, 9.0]  
3       0.1550     10   (9.0, 10.0]  
4       0.0550      7  (0.999, 7.0]  
...        ...    ...           ...  
4172    0.2490     11  (10.0, 12.0]  
4173    0.2605     10   (9.0, 10.0]  
4174    0.3080      9    (7.0, 9.0]  
4175    0.2960     10   (9.0, 10.0]  
4176    0.4950     12  (10.0, 12.0]  

[4177 rows x 11 columns]

### sklearn preprocessing

In [18]:
from sklearn.preprocessing import KBinsDiscretizer

In [19]:
est = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')

In [20]:
X = df[['rings', 'length']]

In [21]:
est.fit_transform(X)

array([[1., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 2.],
       [0., 2.],
       [1., 2.]])

In [23]:
ut.discretize_dataframe(df, ['rings', 'length'])

Binning rings
Binning length


rings_GRP length_GRP
0         High        Low
1          Low        Low
2          Mid        Mid
3          Mid        Low
4          Low        Low
...        ...        ...
4172       Mid        Mid
4173       Mid        Mid
4174       Mid       High
4175       Mid       High
4176      High       High

[4177 rows x 2 columns]

In [25]:
ut.discretize_dataframe(df, ['rings', 'length'], num_bins=5)

Binning rings
Binning length


rings_GRP      length_GRP
0     (12.0, 29.0]   (0.425, 0.51]
1     (0.999, 7.0]  (0.074, 0.425]
2       (7.0, 9.0]   (0.51, 0.575]
3      (9.0, 10.0]   (0.425, 0.51]
4     (0.999, 7.0]  (0.074, 0.425]
...            ...             ...
4172  (10.0, 12.0]   (0.51, 0.575]
4173   (9.0, 10.0]  (0.575, 0.625]
4174    (7.0, 9.0]  (0.575, 0.625]
4175   (9.0, 10.0]  (0.575, 0.625]
4176  (10.0, 12.0]  (0.625, 0.815]

[4177 rows x 2 columns]

In [26]:
pd.qcut(range(5), 3, labels=["good", "medium", "bad"])

[good, good, medium, bad, bad]
Categories (3, object): [good < medium < bad]

In [27]:
pd.qcut(range(5), 5, labels=["good", "medium", "bad"])

ValueError: Bin labels must be one fewer than the number of bin edges

In [35]:
from imp import reload

In [58]:
reload(ut)

<module 'utility' from '../utility.py'>

In [54]:
import explore as ex

In [56]:
ut.discretize_dataframe(df, ['rings', 'length'], append_column=True, \
                        num_bins=5, group_labels=['a', 'b', 'c', 'd', 'e'] )

index sex  length  diameter  height  whole_wt  shucked_wt  viscera_wt  \
0         0   M   0.455     0.365   0.095    0.5140      0.2245      0.1010   
1         1   M   0.350     0.265   0.090    0.2255      0.0995      0.0485   
2         2   F   0.530     0.420   0.135    0.6770      0.2565      0.1415   
3         3   M   0.440     0.365   0.125    0.5160      0.2155      0.1140   
4         4   I   0.330     0.255   0.080    0.2050      0.0895      0.0395   
...     ...  ..     ...       ...     ...       ...         ...         ...   
4172   4172   F   0.565     0.450   0.165    0.8870      0.3700      0.2390   
4173   4173   M   0.590     0.440   0.135    0.9660      0.4390      0.2145   
4174   4174   M   0.600     0.475   0.205    1.1760      0.5255      0.2875   
4175   4175   F   0.625     0.485   0.150    1.0945      0.5310      0.2610   
4176   4176   M   0.710     0.555   0.195    1.9485      0.9455      0.3765   

      shell_wt  rings rings_GRP rings_GRP length_GRP  
0       0.1500     15      high         e          b  
1       0.0700      7       low         a          a  
2       0.2100      9       mid         b          c  
3       0.1550     10       mid         c          b  
4       0.0550      7       low         a          a  
...        ...    ...       ...       ...        ...  
4172    0.2490     11       mid         d          c  
4173    0.2605     10       mid         c          d  
4174    0.3080      9       mid         b          d  
4175    0.2960     10       mid         c          d  
4176    0.4950     12      high         d          e  

[4177 rows x 13 columns]

### Date

In [57]:
ut.datestr2date("2020-04-15")

datetime.date(2020, 4, 15)

In [60]:
ut.shift_by_month("2010-03-16", 2)

datetime.date(2010, 5, 16)

In [62]:
import datetime

In [63]:
ut.shift_by_month(datetime.date(2020, 4, 15), -2)

datetime.date(2020, 2, 15)

In [70]:
d = pd.DataFrame({'d': [datetime.date(2020, 2, 15), datetime.date(2010, 7, 15)] })
d

d
0  2020-02-15
1  2010-07-15

In [74]:
d['d'].apply(ut.shift_by_month, args=(2,))

0    2020-04-15
1    2010-09-15
Name: d, dtype: object

### Columns

In [168]:
reload(ut)

<module 'utility' from '../utility.py'>

In [75]:
S = ut.DiscreteSampler(['M', 'F'], [2, 4])

In [76]:
S.choice()

'M'

In [77]:
S._cdf()

[0.3333333333333333, 1.0]

In [169]:
dm = ut.create_artificial_col(d, ['M', 'F'], [0.2, 0.8], 'sex')

In [170]:
dm

d sex
0  2020-02-15   F
1  2010-07-15   M

In [171]:
ut.create_missing_columns(dm, 'sex', p=1.0)

d   sex
0  2020-02-15  None
1  2010-07-15  None

In [172]:
ut.create_missing_columns(dm, 'sex', p=0.5)

d   sex
0  2020-02-15  None
1  2010-07-15     M

In [173]:
df.head()

index   sex  length  diameter  height  whole_wt  shucked_wt  viscera_wt  \
0      0  None   0.455     0.365   0.095    0.5140      0.2245      0.1010   
1      1     M   0.350     0.265   0.090    0.2255      0.0995      0.0485   
2      2     F   0.530     0.420   0.135    0.6770      0.2565      0.1415   
3      3     M   0.440     0.365   0.125    0.5160      0.2155      0.1140   
4      4     I   0.330     0.255   0.080    0.2050      0.0895      0.0395   

   shell_wt  rings rings_GRP  
0     0.150     15      high  
1     0.070      7       low  
2     0.210      9       mid  
3     0.155     10       mid  
4     0.055      7       low

In [177]:
dm = df[['length']]

In [178]:
dm.head()

length
0   0.455
1   0.350
2   0.530
3   0.440
4   0.330

In [191]:
mdf = ut.create_missing_columns(dm, 'length', p=0.5)
mdf.head()

length
0     NaN
1     NaN
2     NaN
3    0.44
4     NaN

In [192]:
ex.count_missing(mdf)

{'length': 2088}

In [193]:
mdf.shape

(4177, 1)

In [198]:
np.sort(mdf['length'])

array([0.075, 0.13 , 0.14 , ...,   nan,   nan,   nan])

### Extract

In [200]:
(x, y, features) = ut.extract_feature_target(df, 'sex')

In [201]:
x

index  length  diameter  height  whole_wt  shucked_wt  viscera_wt  \
0         0   0.455     0.365   0.095    0.5140      0.2245      0.1010   
1         1   0.350     0.265   0.090    0.2255      0.0995      0.0485   
2         2   0.530     0.420   0.135    0.6770      0.2565      0.1415   
3         3   0.440     0.365   0.125    0.5160      0.2155      0.1140   
4         4   0.330     0.255   0.080    0.2050      0.0895      0.0395   
...     ...     ...       ...     ...       ...         ...         ...   
4172   4172   0.565     0.450   0.165    0.8870      0.3700      0.2390   
4173   4173   0.590     0.440   0.135    0.9660      0.4390      0.2145   
4174   4174   0.600     0.475   0.205    1.1760      0.5255      0.2875   
4175   4175   0.625     0.485   0.150    1.0945      0.5310      0.2610   
4176   4176   0.710     0.555   0.195    1.9485      0.9455      0.3765   

      shell_wt  rings rings_GRP  
0       0.1500     15      high  
1       0.0700      7       low  
2       0.2100      9       mid  
3       0.1550     10       mid  
4       0.0550      7       low  
...        ...    ...       ...  
4172    0.2490     11       mid  
4173    0.2605     10       mid  
4174    0.3080      9       mid  
4175    0.2960     10       mid  
4176    0.4950     12      high  

[4177 rows x 10 columns]

In [202]:
y

sex
0     None
1        M
2        F
3        M
4        I
...    ...
4172     F
4173     M
4174     M
4175     F
4176     M

[4177 rows x 1 columns]

In [203]:
features

['height',
 'shell_wt',
 'rings',
 'length',
 'whole_wt',
 'index',
 'shucked_wt',
 'rings_GRP',
 'diameter',
 'viscera_wt']

In [239]:
reload(ut)

<module 'utility' from '../utility.py'>

In [240]:
(x, y, features) = ut.extract_feature_target(df, 'sex', todf=False)

In [241]:
x

array([[0.095, 0.15, 15, ..., 'high', 0.365, 0.10099999999999999],
       [0.09, 0.07, 7, ..., 'low', 0.265, 0.0485],
       [0.135, 0.21, 9, ..., 'mid', 0.42, 0.1415],
       ...,
       [0.205, 0.308, 9, ..., 'mid', 0.475, 0.2875],
       [0.15, 0.29600000000000004, 10, ..., 'mid', 0.485, 0.261],
       [0.195, 0.495, 12, ..., 'high', 0.555, 0.3765]], dtype=object)

In [242]:
x.shape

(4177, 10)

In [243]:
y

array([None, 'M', 'F', ..., 'M', 'F', 'M'], dtype=object)

In [244]:
y.shape

(4177,)

In [245]:
features

['height',
 'shell_wt',
 'rings',
 'length',
 'whole_wt',
 'index',
 'shucked_wt',
 'rings_GRP',
 'diameter',
 'viscera_wt']

In [250]:
matrix = x[:3, :4]
matrix

array([[0.095, 0.15, 15, 0.455],
       [0.09, 0.07, 7, 0.35],
       [0.135, 0.21, 9, 0.53]], dtype=object)

### slicing

In [251]:
ut.npslice(matrix, [1, 0], [2, 1])

array([[0.09],
       [0.135]], dtype=object)

In [252]:
ut.npslice(matrix, [1, 0], [2, 2])

array([[0.09, 0.07],
       [0.135, 0.21]], dtype=object)

In [253]:
ut.npslice(matrix, [0, 0], [2, 1])

array([[0.095],
       [0.09]], dtype=object)

In [254]:
ut.npslice(matrix, [1, 1], [2, 2])

array([[0.07, 7],
       [0.21, 9]], dtype=object)

### Encoder

In [258]:
ut.one_hot_encoded([1,2,3])

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [261]:
coded = ut.one_hot_encoded([7,2,3])
coded

array([[0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]])

In [265]:
reload(ut)

<module 'utility' from '../utility.py'>

In [266]:
ut.one_hot_decoded(coded)

[7, 2, 3]

### sorting

In [282]:
reload(ut)

<module 'utility' from '../utility.py'>

In [283]:
ut.select_and_sort([4,5,None,7, np.nan, 1])

[1, 4, 5, 7, None, nan]